# Generated by Django 5.0.4 on 2025-01-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_approved',
        ),
    ]
