# Generated by Django 5.0.4 on 2025-01-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0009_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image',
        ),
    ]
