# Generated by Django 5.0.4 on 2025-01-09 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0011_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='servicer.staff'),
        ),
    ]
