# Generated by Django 5.0.4 on 2025-01-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0012_cars_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
