# Generated by Django 5.0.4 on 2025-01-09 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicer', '0015_remove_vehicle_owner_booking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='servicer.staff'),
        ),
    ]
